-- Website operating modes.
alter table public.site_settings
  add column if not exists site_mode text not null default 'normal',
  add column if not exists maintenance_message text not null default 'Thư viện đang được chăm sóc và sẽ sớm hoạt động trở lại.',
  add column if not exists maintenance_until timestamptz,
  add column if not exists mode_updated_at timestamptz not null default now(),
  add column if not exists mode_updated_by uuid references auth.users(id) on delete set null;
do $$ begin if not exists (select 1 from pg_constraint where conname='site_settings_mode_valid' and conrelid='public.site_settings'::regclass) then alter table public.site_settings add constraint site_settings_mode_valid check (site_mode in ('normal','read_only','maintenance','locked')); end if; end $$;
create or replace function public.site_reader_writes_allowed() returns boolean language sql stable security invoker set search_path=public as $$ select coalesce((select site_mode='normal' from public.site_settings where id=1),true); $$;
grant execute on function public.site_reader_writes_allowed() to anon, authenticated;
do $$ declare target_table text; operation text; policy_name text; begin foreach target_table in array array['profiles','favorites','follows','reading_progress','reading_history','comments','comment_replies','comment_likes','chapter_likes','ratings','notifications','poll_votes','inbox','views'] loop foreach operation in array array['insert','update','delete'] loop policy_name:='site_mode_guard_'||operation; execute format('drop policy if exists %I on public.%I',policy_name,target_table); if operation='insert' then execute format('create policy %I on public.%I as restrictive for insert to anon, authenticated with check (public.is_admin() or (select public.site_reader_writes_allowed()))',policy_name,target_table); elsif operation='update' then execute format('create policy %I on public.%I as restrictive for update to anon, authenticated using (public.is_admin() or (select public.site_reader_writes_allowed())) with check (public.is_admin() or (select public.site_reader_writes_allowed()))',policy_name,target_table); else execute format('create policy %I on public.%I as restrictive for delete to anon, authenticated using (public.is_admin() or (select public.site_reader_writes_allowed()))',policy_name,target_table); end if; end loop; end loop; end $$;