/* ViCamBachGiai — stable illustrated avatar pool. No layout changes. */
(function(){
  const A=[
    ['duck','#ffd75b','#e9a92c','duck'],['polar','#f6f0e7','#d7cfc4','bear'],['bear','#b98255','#6e4733','bear'],['penguin','#222936','#f2efe9','penguin'],
    ['cat','#aab3c5','#596276','cat'],['fox','#ef8b3d','#9b4d20','fox'],['rabbit','#f4eee9','#d7b6c8','rabbit'],['capy','#b98255','#73513a','capy'],
    ['dino','#70b58c','#44785d','dino'],['panda','#f4efe8','#20242d','panda'],['chick','#ffd66a','#e6a728','chick'],['hedgehog','#c89b68','#7a5438','hedgehog'],
    ['otter','#c49a72','#76563f','otter'],['corgi','#e99a4a','#9b5a2b','corgi'],['frog','#80b782','#49764d','frog'],['koala','#aeb8c4','#66707c','koala']
  ];
  const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function hash(s){let h=2166136261; for(const c of String(s||'')){h^=c.charCodeAt(0);h=Math.imul(h,16777619)} return h>>>0}
  function keyOf(u){return (u&&(u.user_id||u.id||u.email||u.display_name))||'guest'}
  function svg(spec){const [n,c1,c2,t]=spec; let ears=''; if(/bear|panda|koala/.test(t)) ears='<circle cx="28" cy="28" r="10" fill="'+c2+'"/><circle cx="72" cy="28" r="10" fill="'+c2+'"/>'; if(/cat|fox|corgi/.test(t)) ears='<path d="M22 34L28 13l16 18M78 34L72 13 56 31" fill="'+c2+'"/>'; if(t==='rabbit') ears='<ellipse cx="34" cy="18" rx="8" ry="18" fill="'+c1+'"/><ellipse cx="66" cy="18" rx="8" ry="18" fill="'+c1+'"/>'; if(t==='penguin') ears='';
    const face=t==='penguin'?'<ellipse cx="50" cy="54" rx="28" ry="34" fill="#252c39"/><ellipse cx="50" cy="60" rx="21" ry="25" fill="#f4efe9"/><path d="M45 57h10l-5 5z" fill="#f0a63d"/>':t==='duck'||t==='chick'?'<ellipse cx="50" cy="52" rx="30" ry="31" fill="'+c1+'"/><ellipse cx="50" cy="61" rx="13" ry="7" fill="#e9a33b"/>':'<circle cx="50" cy="52" r="31" fill="'+c1+'"/><ellipse cx="50" cy="63" rx="15" ry="11" fill="rgba(255,255,255,.35)"/>';
    const extras=t==='frog'?'<circle cx="34" cy="29" r="9" fill="'+c1+'"/><circle cx="66" cy="29" r="9" fill="'+c1+'"/>':t==='hedgehog'?'<path d="M18 52Q17 24 50 16q33 8 32 36-5-10-13-14-8-14-19-20-12 7-19 20-8 4-13 14z" fill="'+c2+'"/>':'';
    return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#262a45"/><stop offset="1" stop-color="#111628"/></linearGradient></defs><circle cx="50" cy="50" r="49" fill="url(#g)"/><circle cx="50" cy="50" r="46" fill="none" stroke="rgba(174,143,255,.45)"/>'+ears+extras+face+'<circle cx="39" cy="50" r="3.2" fill="#26231f"/><circle cx="61" cy="50" r="3.2" fill="#26231f"/><path d="M45 69q5 5 10 0" fill="none" stroke="#5d4435" stroke-width="2.2" stroke-linecap="round"/></svg>';
  }
  function dataFor(u){const i=hash(keyOf(u))%A.length; return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(svg(A[i]));}
  function realAvatar(u){const a=u&&u.avatar?String(u.avatar):''; return /^(https?:|data:image\/|covers\/|brand\/)/i.test(a)?a:''}
  function srcFor(u){return realAvatar(u)||dataFor(u)}
  function decorate(el,u,admin){if(!el)return; const src=srcFor(u||{}); el.classList.add('vc-pool-avatar'); if(admin)el.classList.add('vc-admin-avatar'); if(el.tagName==='IMG'){el.src=src;return} let img=el.querySelector(':scope > img.vc-avatar-img'); if(!img){el.textContent='';img=document.createElement('img');img.className='vc-avatar-img';img.alt='';el.appendChild(img)} img.src=src;}
  function feedMap(){const m={comments:{},replies:{}}; try{const f=VCBG.communityFeed({sort:'latest',storyId:''})||[]; f.forEach(c=>{m.comments[String(c.id)]=c.user||{};(c.replies||[]).forEach(r=>m.replies[String(r.id)]=r.user||{})})}catch(_){} return m}
  function drawerMap(){const m={};try{document.querySelectorAll('.reader-page').forEach(()=>{}); const raw=(location.hash||'').replace(/^#/,''); const mt=raw.match(/^\/truyen\/([^/?]+)\/chuong-(\d+)/); if(!mt)return m; const s=VCBG.getStoryBySlug(mt[1]); if(!s)return m; const ch=VCBG.getChapter(s.id,Number(mt[2])); if(!ch)return m; (VCBG.listComments(ch.id)||[]).forEach(c=>m[String(c.id)]=c.user||{})}catch(_){} return m}
  let busy=false;
  function sync(){if(busy)return;busy=true;requestAnimationFrame(()=>{busy=false; if(!window.VCBG)return; const me=VCBG.currentUser&&VCBG.currentUser(); document.querySelectorAll('.avatar-chip').forEach(el=>decorate(el,me&&me.profile,me&&me.role==='admin')); const fm=feedMap(); document.querySelectorAll('.sig-card[data-cid]').forEach(card=>{const el=card.querySelector(':scope > .sig-ava');decorate(el,fm.comments[card.dataset.cid],card.querySelector('.sig-badge.staff'))}); document.querySelectorAll('.sig-reply[data-rid]').forEach(card=>decorate(card.querySelector('.sig-ava'),fm.replies[card.dataset.rid],card.querySelector('.sig-badge.staff'))); document.querySelectorAll('.sig-compose .sig-ava').forEach(el=>decorate(el,me&&me.profile,me&&me.role==='admin')); const dm=drawerMap(); document.querySelectorAll('.vc-comment[data-comment-id]').forEach(card=>decorate(card.querySelector(':scope > .vc-avatar'),dm[card.dataset.commentId])); document.querySelectorAll('.vc-reply .vc-avatar').forEach((el,i)=>{if(!el.querySelector('img')) decorate(el,{id:'reply-'+i})}); document.querySelectorAll('[data-avatar-user]').forEach(el=>decorate(el,{id:el.getAttribute('data-avatar-user')})); });}
  window.VICAM_AVATARS={srcFor,decorate,sync,pool:A.map(x=>x[0])};
  new MutationObserver(sync).observe(document.documentElement,{childList:true,subtree:true}); window.addEventListener('load',sync); window.addEventListener('hashchange',()=>setTimeout(sync,60)); setTimeout(sync,80);
})();